name: myenv
channels:
  - conda-forge
  - ambermd
dependencies:
  - openmm=7.6
  - pdbfixer
  - matplotlib
  - mdtraj
  - nglview
  - numpy
  - pandas
  - seaborn
  - scipy
  - ipython
  - parmed
  - pip
  - pip:
    - cython
    - pinda
