input_folder: 'E:\\MolecularDynamicsApp\\src\\MolecularDynamics\\data\\input'
output_folder: 'E:\\MolecularDynamicsApp\\src\\MolecularDynamics\\data\\output'
rawData: 'E:\\MolecularDynamicsApp\\src\\MolecularDynamics\\data\\preparedData'